name: valuta
description: A minimal and type-safe Dart currency conversion library.
homepage: https://github.com/Moelfarri
repository: https://github.com/Moelfarri/currency
issue_tracker: https://github.com/Moelfarri/currency/issues
documentation: https://github.com/Moelfarri/currency/blob/main/README.md
version: 1.0.0
environment:
  sdk: ^3.6.2
dependencies:
  http: ^1.4.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
