name: currency
description: A minimal and type-safe Dart currency conversion library.
homepage: https://dev.azure.com/inline-test/InlineX%20Flutter%20Monorepo
repository: https://dev.azure.com/inline-test/_git/InlineX%20Flutter%20Monorepo
issue_tracker: https://dev.azure.com/inline-test/InlineX%20Flutter%20Monorepo/_workitems/assignedtome/
documentation: https://inlinetest.atlassian.net/wiki/spaces/IX3/pages/65575/Mobile+App?cloudId=dd72f531-6a40-4b6c-a8ad-87ff7aca5fd2
version: 1.0.0
environment:
  sdk: ^3.6.2
dependencies:
  # path: ^1.8.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
